spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dragenda_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

admin:
  seed:
    password: ${ADMIN_SEED_PASSWORD:admin123@Dev}  # default apenas para dev local

logging:
  level:
    com.dragenda: DEBUG
    org.springframework.security: DEBUG
